"""
Brain-Rot Shorts Factory — LLM-generated titles and descriptions
"""

import logging
import re
from typing import Any

import config
from ollama_client import chat, generate_json, is_ollama_available
from yt_uploader import TAGS

log = logging.getLogger(__name__)

SYSTEM_PROMPT = """You write YouTube Short captions for a regular gamer who posts their own clips.
Sound like a real person typing on their phone after a match — not a brand, bot, or marketing copy.

Voice rules:
- First person (I, me, my). Casual and natural.
- Short sentences. One honest reaction beats three hype lines.
- It's okay to be understated ("kinda clean ngl") or hyped ("I still don't know how I hit that").
- Match the hype score: low = chill/self-deprecating, high = excited but still human.
- Put hashtags on the last line only. Never weave hashtags into sentences.

Never use these AI/corporate phrases:
- "automated", "highlight reel", "in this video", "witness", "showcase", "epic gaming moment"
- "don't forget to like and subscribe", "smash that like button"
- "POTG" or "insane outplay" unless the clip summary clearly supports it
"""

METADATA_PROMPT = """Write YouTube Short metadata for my {game} clip.

What happened in the clip: {summary}
How hype it was (1-10): {hype}

Title: catchy, under 90 chars, 1-2 hashtags max, sounds like something a player would actually post.

Description: 2-4 short lines in my voice — what happened, how I felt, maybe one line of context (ranked, late fight, etc.). End with a blank line then hashtags:
#shorts #{game_lower} #gaming

Respond with JSON only:
{{
  "title": "...",
  "description": "...",
  "tags": ["overwatch", "shorts", "gaming"]
}}"""

# Phrases that make descriptions sound robotic — stripped in post-processing
AI_TELLS = [
    r"\bautomated\b",
    r"\bgenerated by\b",
    r"\bhighlight reel\b",
    r"\bin this (video|clip|short)\b",
    r"\bwitness\b",
    r"\bshowcase\b",
    r"\bepic gaming moment\b",
    r"\bdon't forget to (like|subscribe)\b",
    r"\bsmash that like\b",
    r"\bas an ai\b",
    r"\bbrain-rot factory\b",
]


def _humanize_description(text: str, game: str) -> str:
    """Light cleanup so descriptions read like a person wrote them."""
    if not text:
        return text

    cleaned = text.strip()
    for pattern in AI_TELLS:
        cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE)

    cleaned = re.sub(r"[ \t]+", " ", cleaned)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)

    lines = [ln.strip() for ln in cleaned.splitlines()]
    body_lines: list[str] = []
    tag_lines: list[str] = []
    for ln in lines:
        if not ln:
            continue
        if ln.startswith("#") or (re.search(r"#\w", ln) and len(ln.split()) <= 8):
            tag_lines.append(ln)
        elif len(ln.split()) >= 5:
            body_lines.append(ln)

    game_tag = game.lower().replace(" ", "")
    default_tags = f"#shorts #{game_tag} #gaming"
    if not tag_lines:
        tag_lines = [default_tags]
    elif not any("shorts" in t.lower() for t in tag_lines):
        tag_lines.append(default_tags)

    body = "\n".join(body_lines).strip()
    tags = " ".join(tag_lines)
    if body:
        return f"{body}\n\n{tags}"
    return tags


def _fallback_metadata(summary: str, hype: float) -> dict[str, Any]:
    game = config.GAME_NAME
    summary = summary or "Had a decent moment in ranked"

    if hype >= 8:
        opener = "Still not over this play tbh"
    elif hype >= 6:
        opener = "This one felt pretty good ngl"
    else:
        opener = "Small win but I'll take it"

    description = _humanize_description(
        f"{opener}\n\n{summary}\n\n#shorts #{game.lower()} #gaming",
        game,
    )
    return {
        "title": f"ok this was kinda clean 💀 #shorts #{game.lower()}",
        "description": description,
        "tags": TAGS[:8],
    }


def generate_metadata(summary: str, hype_score: float) -> dict[str, Any]:
    game = config.GAME_NAME
    try:
        from settings import load_settings
        s = load_settings()
        game = s.get("game_name", game)
        model = s.get("text_model", config.TEXT_MODEL)
    except Exception:
        model = config.TEXT_MODEL

    if not is_ollama_available():
        log.warning("Ollama offline — using fallback metadata")
        return _fallback_metadata(summary, hype_score)

    prompt = METADATA_PROMPT.format(
        game=game,
        summary=summary or "Something happened in a team fight",
        hype=hype_score,
        game_lower=game.lower().replace(" ", ""),
    )

    try:
        result = generate_json(model, prompt, system=SYSTEM_PROMPT)
        tags = list(result.get("tags") or [])
        merged_tags = list(dict.fromkeys(tags + TAGS))[:15]

        title = (result.get("title") or "").strip()
        description = _humanize_description(
            (result.get("description") or "").strip(),
            game,
        )

        if not title:
            title = _fallback_metadata(summary, hype_score)["title"]
        body_word_count = len(description.replace("#", "").split())
        if not description or description.startswith("#") or body_word_count < 5:
            description = _fallback_metadata(summary, hype_score)["description"]

        return {
            "title": title,
            "description": description,
            "tags": merged_tags,
        }
    except Exception as exc:
        log.error("Metadata generation failed: %s", exc)
        # Second attempt with a simpler direct prompt (often more natural)
        try:
            raw = chat(
                model,
                f"""Write a YouTube Short description for my {game} clip like you're texting a friend.

Clip: {summary or 'ranked match moment'}
Hype: {hype_score}/10

2-4 casual first-person lines. No marketing speak. End with #shorts #{game.lower()} #gaming
Description only, no JSON.""",
                system=SYSTEM_PROMPT,
            )
            description = _humanize_description(raw.strip(), game)
            fb = _fallback_metadata(summary, hype_score)
            return {
                "title": fb["title"],
                "description": description,
                "tags": fb["tags"],
            }
        except Exception as exc2:
            log.error("Metadata fallback chat failed: %s", exc2)
            return _fallback_metadata(summary, hype_score)
